name: Documentation Update
description: Describe this issue found in the documentation
title: "[Doc]: "
labels: ["documentation", "triage"]
assignees: 
  - B3nz01d
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: A short description of what the issue is.
    validations:
      required: true
  - type: textarea
    id: location
    attributes:
      label: Documentation Location
      description: Where in the documentation should there be an update.
    validations:
      required: true
  