name: Epic Request
description: Suggest a new Epic to be added to the backlog.
title: "[Epic]: "
labels: ["Epic", "Triage"]
assignees: 
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
