name: Epic Request
description: Suggest a new Epic to be added to the backlog.
title: "[Epic]: "
labels: ["Epic", "Triage"]
assignees: 
  - B3nz01d
body:
  - type: checkboxes
    attributes:
      label: Prerequisites
      description: Take a couple minutes to help our maintainers work faster.
      options:
        - label: I have [searched the backlog](https://github.com/Orange-OpenSource/ods-ios/issues) for duplicate or closed feature requests
          required: true
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
